version: "3.7"

services:

  mariadb:
    restart: always
    image: mariadb:10.6
    container_name: gsi.mariadb.dev.local.com
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    ports:
    - 3306:3306
    environment:
      - MARIADB_PASSWORD=${DB_ROOT_PASSWORD:-123}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-123}
    volumes:
      - mariadb-data:/var/lib/mysql

  redis-cache:
    restart: always
    container_name: gsi.redis.cache.dev.local.com
    image: redis:alpine

  redis-queue:
    restart: always
    image: redis:alpine
    container_name: gsi.redis.queue.dev.local.com

  redis-socketio:
    restart: always
    image: redis:alpine
    container_name: gsi.redis.socketio.dev.local.com

  frappe:
    restart: always
    user: frappe
    build:
      dockerfile: images/frappe/Dockerfile
      context: .
    command: sleep infinity
    container_name: gsi.erpnext.dev.local.com
    links:
      - mariadb
      - redis-cache
      - redis-socketio
      - redis-queue
    environment:
      - FRAPPE_VERSION=${FRAPPE_VERSION:-version-14}
      - ERPNEXT_VERSION=${ERPNEXT_VERSION:-version-14}
      #- CUSTOM_APPS=$CUSTOM_APPS
      - SERVER_PORT=${SERVER_PORT:-8000}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-123}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-12345}
      - SITE_NAME=${SITE_NAME:-gsi.erpnext.dev.local.com}
      - DEVELOPER_MODE=${DEVELOPER_MODE:-1}
      - DB_NAME=${DB_NAME:-gsi_db}
      - DEV_SERVER=1
    volumes:
      - ..:/workspace:cached
      - ./src:/home/frappe/frappe-bench
    working_dir: /home/frappe/frappe-bench
    ports:
      - 8000-8005:8000-8005
      - 9000-9005:9000-9005

#  frappe_debugger:
#    image: frappe/bench:latest
#    container_name: gsi.erpnext.debugger.dev.local.com
#    volumes_from:
#      - frappe
#    env_file:
#      - .env

volumes:
  mariadb-data:
